/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pinnacle.cafe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class pay extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form pay
     */
    public pay() {
        initComponents();
    }

    private void showTableData() {

        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pinnacle", "root", "");
            String sql = "SELECT * FROM Employee_list";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnreset = new javax.swing.JButton();
        jbtndeduct = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtnexit1 = new javax.swing.JButton();
        jbtnshowlist = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jtxtprevioussalary = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelpsalary = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbtnpercent = new javax.swing.JRadioButton();
        jrbtnamount = new javax.swing.JRadioButton();
        jtxtpercent = new javax.swing.JTextField();
        jtxtamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(99, 112, 248), 5, true));

        jbtnreset.setBackground(new java.awt.Color(255, 255, 255));
        jbtnreset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnreset.setForeground(new java.awt.Color(99, 112, 248));
        jbtnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jbtndeduct.setBackground(new java.awt.Color(255, 255, 255));
        jbtndeduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndeduct.setForeground(new java.awt.Color(99, 112, 248));
        jbtndeduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_16x16.gif"))); // NOI18N
        jbtndeduct.setText("Deduct");
        jbtndeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeductActionPerformed(evt);
            }
        });

        jbtnupdate.setBackground(new java.awt.Color(255, 255, 255));
        jbtnupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnupdate.setForeground(new java.awt.Color(99, 112, 248));
        jbtnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save-icon.png"))); // NOI18N
        jbtnupdate.setText("Add");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });

        jbtnexit1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnexit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnexit1.setForeground(new java.awt.Color(99, 112, 248));
        jbtnexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jbtnexit1.setText("Return");
        jbtnexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexit1ActionPerformed(evt);
            }
        });

        jbtnshowlist.setBackground(new java.awt.Color(255, 255, 255));
        jbtnshowlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnshowlist.setForeground(new java.awt.Color(99, 112, 248));
        jbtnshowlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list.png"))); // NOI18N
        jbtnshowlist.setText("Show list");
        jbtnshowlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnshowlistActionPerformed(evt);
            }
        });

        jtxtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDActionPerformed(evt);
            }
        });

        jtxtprevioussalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtprevioussalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtprevioussalaryActionPerformed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelID.setText("ID:");

        jLabelpsalary.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelpsalary.setText("Basic Salary: ");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setText("Add or deduct salary by:");

        jrbtnpercent.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jrbtnpercent.setText("Percentage(%)");
        jrbtnpercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnpercentActionPerformed(evt);
            }
        });

        jrbtnamount.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jrbtnamount.setText("Amount");
        jrbtnamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnamountActionPerformed(evt);
            }
        });

        jtxtpercent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtpercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpercentActionPerformed(evt);
            }
        });

        jtxtamount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Percentage:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setText("Amount:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelpsalary)
                        .addGap(36, 36, 36)
                        .addComponent(jtxtprevioussalary, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jrbtnpercent)
                        .addGap(47, 47, 47)
                        .addComponent(jrbtnamount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(jtxtpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jtxtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtnreset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtndeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtnshowlist, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnexit1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelpsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtprevioussalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtnpercent)
                    .addComponent(jrbtnamount))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtpercent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnshowlist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 393, 530));

        jbtnexit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073741823, 782, 62, 45));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Designation", "Number", "Email", "Salary", "Joining date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 630, 460));

        jPanel4.setBackground(new java.awt.Color(99, 112, 248));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Salary");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(806, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 1053, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1120, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnshowlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnshowlistActionPerformed
        showTableData();
    }//GEN-LAST:event_jbtnshowlistActionPerformed

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed

    private void jrbtnamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnamountActionPerformed
        // TODO add your handling code here:

        jrbtnamount.setSelected(true);
        jrbtnpercent.setSelected(false);
        //r_percentage.setEnabled(false);
        jtxtpercent.setEnabled(false);
        jtxtamount.setEditable(true);
        jtxtamount.setEnabled(true);
        jtxtpercent.setText("");

    }//GEN-LAST:event_jrbtnamountActionPerformed

    private void jtxtpercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpercentActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jtxtpercentActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (x == 0) {

            int salary = Integer.parseInt(jtxtprevioussalary.getText());

            if (jrbtnpercent.isSelected() == true) {
                int getPercentage = Integer.parseInt(jtxtpercent.getText());
                int calcPercentage = salary / 100 * getPercentage + salary;
                String xP = String.valueOf(calcPercentage);
                jtxtprevioussalary.setText(xP);
            } else if (jrbtnamount.isSelected() == true) {
                int getAmt = Integer.parseInt(jtxtamount.getText());
                int calcAmount = salary + getAmt;
                String xA = String.valueOf(calcAmount);
                jtxtprevioussalary.setText(xA);
            }

            //catch (Exception e)
            //JOptionPane.showMessageDialog(null,e);
            try {

                String value1 = jtxtID.getText();
                String value2 = jtxtprevioussalary.getText();

                String sql = "update employee_list set id='" + value1 + "',Salary='" + value2 + "' where id='" + value1 + "'";

                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {

                try {
                    rs.close();
                    pst.close();

                } catch (Exception e) {

                }
                showTableData();
            }

        }
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jtxtprevioussalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtprevioussalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprevioussalaryActionPerformed

    private void jrbtnpercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnpercentActionPerformed
        jrbtnpercent.setSelected(true);
        jrbtnamount.setSelected(false);
        //r_amount.setEnabled(false);
        jtxtamount.setEnabled(false);
        jtxtpercent.setEditable(true);
        jtxtpercent.setEnabled(true);
        jtxtamount.setText("");
    }//GEN-LAST:event_jrbtnpercentActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtID.setText("");
        jtxtprevioussalary.setText("");
        jtxtpercent.setText("");
        jtxtamount.setText("");

    }//GEN-LAST:event_jbtnresetActionPerformed
    private JFrame frame;
    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure?", "MySQL connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtndeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeductActionPerformed
        int xi = JOptionPane.showConfirmDialog(null, "Are you sure you want to deduct?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (xi == 0) {
            int salary = Integer.parseInt(jtxtprevioussalary.getText());
            if (jrbtnpercent.isSelected() == true) {
                int percentage = Integer.parseInt(jtxtpercent.getText());
                int total_percentage_deduction = salary / 100 * percentage;
                String x = String.valueOf(total_percentage_deduction);
                int sal = salary - total_percentage_deduction;
                String xd = String.valueOf(sal);
                jtxtprevioussalary.setText(xd);
            }

            if (jrbtnamount.isSelected() == true) {
                int deduction = Integer.parseInt(jtxtamount.getText());
                //calculate the total hours of overtime
                int total_amount_deduction = salary - deduction;
                String sd = String.valueOf(total_amount_deduction);
                jtxtprevioussalary.setText(sd);
            }

            try {

                String value1 = jtxtID.getText();
                String value2 = jtxtprevioussalary.getText();

                String sql = "update employee_list set id='" + value1 + "',Salary='" + value2 + "' where id='" + value1 + "'";

                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deducted successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {

                try {
                    rs.close();
                    pst.close();

                } catch (Exception e) {

                }
                showTableData();

            }
        }
    }//GEN-LAST:event_jbtndeductActionPerformed

    private void jbtnexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexit1ActionPerformed
        employee jf1= new employee();
        jf1.show();
        dispose();
    }//GEN-LAST:event_jbtnexit1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here: remove button code
        dispose();
        dashboard dd = new dashboard();
        dd.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelpsalary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtndeduct;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnexit1;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnshowlist;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JRadioButton jrbtnamount;
    private javax.swing.JRadioButton jrbtnpercent;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtpercent;
    private javax.swing.JTextField jtxtprevioussalary;
    // End of variables declaration//GEN-END:variables
}
